CREATE TABLE IF NOT EXISTS reservations
(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    stay_id UUID NOT NULL,
    user_id UUID NOT NULL,
    arrived TIMESTAMP NOT NULL,
    departure TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    check_in BOOLEAN DEFAULT FALSE,
    check_out BOOLEAN DEFAULT FALSE,

    FOREIGN KEY (stay_id) REFERENCES stays(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);