CREATE TABLE IF NOT EXISTS advantages
(
    id uuid NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE,
    image VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);