CREATE TABLE IF NOT EXISTS stays_images
(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    stay_id UUID NOT NULL REFERENCES stays(id) ON DELETE NO ACTION,
    image_name VARCHAR(255) NOT NULL,
    is_main BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);