networks:
  iod-net:
    driver: bridge

services:
  kafka-ui:
    container_name: kafka-ui
    restart: always
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - '9080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=iod
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-1:9090
    networks:
      - iod-net

  kafka-1:
    image: bitnami/kafka:3.8.1
    restart: always
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka_data/1:/kafka
    networks:
      - iod-net

#networks:
#  iod-net:
#    driver: bridge
#
#services:
#  kafka-ui:
#    container_name: kafka-ui
#    restart: always
#    image: provectuslabs/kafka-ui:v0.7.2
#    ports:
#      - '9080:8080'
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=iod
#      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-1:9090,kafka-2:9090,kafka-3:9090
#    networks:
#      - iod-net
#
#  kafka-1:
#    image: bitnami/kafka:3.8.1
#    restart: always
#    ports:
#      - "9094:9094"
#    environment:
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_NODE_ID=1
#      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
#      - KAFKA_CFG_PROCESS_ROLES=controller,broker
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9094
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ./kafka_data/1:/kafka
#    networks:
#      - iod-net

#  kafka-2:
#    image: bitnami/kafka:3.8.1
#    restart: always
#    ports:
#      - "9095:9095"
#    environment:
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_NODE_ID=2
#      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
#      - KAFKA_CFG_PROCESS_ROLES=controller,broker
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9095
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://${HOSTNAME:-localhost}:9095
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ./kafka_data/2:/kafka
#    networks:
#      - iod-net
#
#  kafka-3:
#    image: bitnami/kafka:3.8.1
#    restart: always
#    ports:
#      - "9096:9096"
#    environment:
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_NODE_ID=3
#      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
#      - KAFKA_CFG_PROCESS_ROLES=controller,broker
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://${HOSTNAME:-localhost}:9096
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ./kafka_data/3:/kafka
#    networks:
#      - iod-net