FROM golang:alpine

WORKDIR /app

COPY ./cmd/migrator/citiesmigrator.go .
COPY ./cmd/migrator/cities.json .

RUN go mod init cities-migrator
RUN go mod tidy
RUN go build -o citiesmigrator citiesmigrator.go