version: '3.8'

networks:
  proxynet:
    driver: bridge

services:
  db:
    image: postgres
    networks:
      - proxynet
    expose:
      - '5433'
    env_file: .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy


volumes:
  local_postgres_data: