version: '3.8'

networks:
  proxynet:
    driver: bridge

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    expose:
#      - '8080'
#    ports:
#      - '8080:8080'

  db:
    image: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    networks:
      - proxynet
    ports:
      - '5432:5432'
    volumes:
      - local_postgres_data:/var/lib/postgresql/data



volumes:
  local_postgres_data: