version: "3.1"
networks:
  proxynet:
    driver: bridge

volumes:
  local_postgres_data:

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - proxynet
    depends_on:
      - postgresdb


  postgresdb:
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - proxynet
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
