version: '3.8'

networks:
  proxynet:
    driver: bridge

services:
#  app:
#    container_name: application
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    environment:
#      - POSTGRES_HOST=db
#    expose:
#      - '8080'
#    ports:
#      - '8080:8080'
#    depends_on:
#      - db
  db:
    image: postgres
    container_name: db
    env_file:
      - ./.env
    expose:
      - '5432'
    ports:
      - '5432:5432'
    networks:
      - proxynet
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

volumes:
  local_postgres_data: