version: '3.8'

networks:
  proxynet:
    driver: bridge

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    expose:
#      - '8080'
#    ports:
#      - '8080:8080'
  db:
    image: postgres
    networks:
      - proxynet
    ports:
      - '5433:5432'
    env_file: .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

volumes:
  local_postgres_data: