version: "3.7"

networks:
  proxynet:
    driver: bridge

volumes:
  local_postgres_data:

services:
  db:
    container_name: db
    restart: always
    image: postgres:13
    env_file: ./.env
    expose:
      - "5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    networks:
      - proxynet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  migrate:
    image: migrate/migrate
    volumes:
      - ./cmd/migrator/migrations:/migrations
    command: [ "-source", "file://migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", "up" ]
    networks:
      - proxynet
    depends_on:
      - db
      - migrate-cities-json

  migrate-cities-json:
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile_cities_migrate
    networks:
      - proxynet
    depends_on:
      - db

  server:
    container_name: server
    restart: always
#    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - "8080:8080"
    networks:
      - proxynet
    depends_on:
      - migrate
      - db