// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	stays "github.com/imperatorofdwelling/Full-backend/internal/domain/models/stays"
)

// FavouriteService is an autogenerated mock type for the FavouriteService type
type FavouriteService struct {
	mock.Mock
}

// AddToFavourites provides a mock function with given fields: ctx, userID, stayID
func (_m *FavouriteService) AddToFavourites(ctx context.Context, userID string, stayID string) error {
	ret := _m.Called(ctx, userID, stayID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, stayID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllFavourites provides a mock function with given fields: ctx, userID
func (_m *FavouriteService) GetAllFavourites(ctx context.Context, userID string) ([]stays.StayEntityFav, error) {
	ret := _m.Called(ctx, userID)


	var r0 []favourite.Favourite
	if rf, ok := ret.Get(0).(func(context.Context, string) []favourite.Favourite); ok {

		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]stays.StayEntityFav)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveFromFavourites provides a mock function with given fields: ctx, userID, stayID
func (_m *FavouriteService) RemoveFromFavourites(ctx context.Context, userID string, stayID string) error {
	ret := _m.Called(ctx, userID, stayID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, stayID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFavouriteService interface {
	mock.TestingT
	Cleanup(func())
}

// NewFavouriteService creates a new instance of FavouriteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFavouriteService(t mockConstructorTestingTNewFavouriteService) *FavouriteService {
	mock := &FavouriteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
