// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	message "github.com/imperatorofdwelling/Full-backend/internal/domain/models/message"

	mock "github.com/stretchr/testify/mock"
)

// MessageRepository is an autogenerated mock type for the MessageRepository type
type MessageRepository struct {
	mock.Mock
}

// DeleteMessageByID provides a mock function with given fields: ctx, messageId
func (_m *MessageRepository) DeleteMessageByID(ctx context.Context, messageId string) error {
	ret := _m.Called(ctx, messageId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, messageId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMessageByMessageID provides a mock function with given fields: ctx, messageId
func (_m *MessageRepository) GetMessageByMessageID(ctx context.Context, messageId string) (*message.Message, error) {
	ret := _m.Called(ctx, messageId)

	var r0 *message.Message
	if rf, ok := ret.Get(0).(func(context.Context, string) *message.Message); ok {
		r0 = rf(ctx, messageId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*message.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, messageId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessagesByUserID provides a mock function with given fields: ctx, userId
func (_m *MessageRepository) GetMessagesByUserID(ctx context.Context, userId string) ([]*message.Entity, error) {
	ret := _m.Called(ctx, userId)

	var r0 []*message.Entity
	if rf, ok := ret.Get(0).(func(context.Context, string) []*message.Entity); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*message.Entity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMessageByID provides a mock function with given fields: ctx, messageId, msg
func (_m *MessageRepository) UpdateMessageByID(ctx context.Context, messageId string, msg message.Entity) error {
	ret := _m.Called(ctx, messageId, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, message.Entity) error); ok {
		r0 = rf(ctx, messageId, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMessageRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMessageRepository creates a new instance of MessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMessageRepository(t mockConstructorTestingTNewMessageRepository) *MessageRepository {
	mock := &MessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
