// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	reservation "github.com/imperatorofdwelling/Full-backend/internal/domain/models/reservation"

	stays "github.com/imperatorofdwelling/Full-backend/internal/domain/models/stays"

	uuid "github.com/gofrs/uuid"
)

// ReservationService is an autogenerated mock type for the ReservationService type
type ReservationService struct {
	mock.Mock
}

// CheckReservation provides a mock function with given fields: _a0, _a1, _a2
func (_m *ReservationService) CheckReservation(_a0 context.Context, _a1 *reservation.ReservationEntity, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CheckReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservation.ReservationEntity, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmCheckInReservation provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *ReservationService) ConfirmCheckInReservation(_a0 context.Context, _a1 string, _a2 string, _a3 reservation.ReservationCheckInEntity) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmCheckInReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, reservation.ReservationCheckInEntity) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmCheckOutReservation provides a mock function with given fields: _a0, _a1, _a2
func (_m *ReservationService) ConfirmCheckOutReservation(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmCheckOutReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateReservation provides a mock function with given fields: _a0, _a1, _a2
func (_m *ReservationService) CreateReservation(_a0 context.Context, _a1 *reservation.ReservationEntity, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservation.ReservationEntity, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteReservationByID provides a mock function with given fields: _a0, _a1
func (_m *ReservationService) DeleteReservationByID(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReservationByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllReservationsByUser provides a mock function with given fields: _a0, _a1
func (_m *ReservationService) GetAllReservationsByUser(_a0 context.Context, _a1 uuid.UUID) (*[]reservation.Reservation, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAllReservationsByUser")
	}

	var r0 *[]reservation.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*[]reservation.Reservation, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *[]reservation.Reservation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]reservation.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFreeReservationsByUserID provides a mock function with given fields: ctx, id
func (_m *ReservationService) GetFreeReservationsByUserID(ctx context.Context, id uuid.UUID) (*[]stays.Stay, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFreeReservationsByUserID")
	}

	var r0 *[]stays.Stay
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*[]stays.Stay, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *[]stays.Stay); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]stays.Stay)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOccupiedReservationsByUserID provides a mock function with given fields: ctx, id
func (_m *ReservationService) GetOccupiedReservationsByUserID(ctx context.Context, id uuid.UUID) (*[]stays.StayOccupied, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOccupiedReservationsByUserID")
	}

	var r0 *[]stays.StayOccupied
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*[]stays.StayOccupied, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *[]stays.StayOccupied); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]stays.StayOccupied)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReservationByID provides a mock function with given fields: _a0, _a1
func (_m *ReservationService) GetReservationByID(_a0 context.Context, _a1 uuid.UUID) (*reservation.Reservation, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetReservationByID")
	}

	var r0 *reservation.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*reservation.Reservation, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *reservation.Reservation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateReservation provides a mock function with given fields: _a0, _a1
func (_m *ReservationService) UpdateReservation(_a0 context.Context, _a1 *reservation.ReservationUpdateEntity) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservation.ReservationUpdateEntity) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReservationService creates a new instance of ReservationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservationService {
	mock := &ReservationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
