// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	staysreviews "github.com/imperatorofdwelling/Full-backend/internal/domain/models/staysreviews"

	uuid "github.com/gofrs/uuid"
)

// StaysReviewsRepo is an autogenerated mock type for the StaysReviewsRepo type
type StaysReviewsRepo struct {
	mock.Mock
}

// CheckIfExists provides a mock function with given fields: _a0, _a1
func (_m *StaysReviewsRepo) CheckIfExists(_a0 context.Context, _a1 uuid.UUID) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CheckIfExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateStaysReview provides a mock function with given fields: _a0, _a1
func (_m *StaysReviewsRepo) CreateStaysReview(_a0 context.Context, _a1 *staysreviews.StaysReviewEntity) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateStaysReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *staysreviews.StaysReviewEntity) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteStaysReviewByID provides a mock function with given fields: _a0, _a1
func (_m *StaysReviewsRepo) DeleteStaysReviewByID(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStaysReviewByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllStaysReviews provides a mock function with given fields: _a0
func (_m *StaysReviewsRepo) FindAllStaysReviews(_a0 context.Context) ([]staysreviews.StaysReview, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for FindAllStaysReviews")
	}

	var r0 []staysreviews.StaysReview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]staysreviews.StaysReview, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []staysreviews.StaysReview); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]staysreviews.StaysReview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneStaysReviewByID provides a mock function with given fields: _a0, _a1
func (_m *StaysReviewsRepo) FindOneStaysReviewByID(_a0 context.Context, _a1 uuid.UUID) (*staysreviews.StaysReview, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindOneStaysReviewByID")
	}

	var r0 *staysreviews.StaysReview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*staysreviews.StaysReview, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *staysreviews.StaysReview); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*staysreviews.StaysReview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStaysReviewByID provides a mock function with given fields: _a0, _a1, _a2
func (_m *StaysReviewsRepo) UpdateStaysReviewByID(_a0 context.Context, _a1 *staysreviews.StaysReviewEntity, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStaysReviewByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *staysreviews.StaysReviewEntity, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStaysReviewsRepo creates a new instance of StaysReviewsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStaysReviewsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *StaysReviewsRepo {
	mock := &StaysReviewsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
