// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/imperatorofdwelling/Website-backend/internal/api"
	"github.com/imperatorofdwelling/Website-backend/internal/config"
	"github.com/imperatorofdwelling/Website-backend/internal/db"
	"github.com/imperatorofdwelling/Website-backend/internal/domain/providers"
	providers2 "github.com/imperatorofdwelling/Website-backend/internal/domain/providers/location"
	"log/slog"
)

// Injectors from wire.go:

func InitializeAPI(cfg *config.Config, log *slog.Logger) (*api.ServerHTTP, error) {
	sqlDB, err := db.ConnectToBD(cfg)
	if err != nil {
		return nil, err
	}
	repository := providers.ProvideUserRepository(sqlDB)
	service := providers.ProvideUserService(repository)
	userHandler := providers.ProvideUserHandler(service, log)
	locationRepo := providers2.ProvideLocationRepository(sqlDB)
	locationService := providers2.ProvideLocationService(locationRepo)
	locationHandler := providers2.ProvideLocationHandler(locationService, log)
	serverHTTP := api.NewServerHTTP(cfg, userHandler, locationHandler, log)
	return serverHTTP, nil
}
