// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/advantages/all": {
            "get": {
                "description": "Get all advantages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "advantages"
                ],
                "summary": "Get advantages",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/advantage.Advantage"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/advantages/create": {
            "post": {
                "description": "Create advantage",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "advantages"
                ],
                "summary": "Create Advantage",
                "parameters": [
                    {
                        "type": "file",
                        "description": "image file",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "title of advantage",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created",
                        "schema": {
                            "$ref": "#/definitions/advantage.Advantage"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/advantages/{advantageId}": {
            "delete": {
                "description": "Delete advantage by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "advantages"
                ],
                "summary": "Delete Advantage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "advantage id",
                        "name": "advantageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update advantage by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "advantages"
                ],
                "summary": "Update Advantage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "advantage id",
                        "name": "advantageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "image file",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "title of advantage",
                        "name": "title",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/advantage.Advantage"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/locations/{locationName}": {
            "get": {
                "description": "Find city by matching name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "locations"
                ],
                "summary": "Find city by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "location name match",
                        "name": "locationName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/location.Location"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticates an existing user and returns a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login an existing user",
                "parameters": [
                    {
                        "description": "Login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/registration": {
            "post": {
                "description": "Creates a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.Registration"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/reservation/create": {
            "post": {
                "description": "Create reservation (arrived and departure should be TIMESTAMP type)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "Create Reservation",
                "parameters": [
                    {
                        "description": "Create reservation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reservation.ReservationEntity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/reservation/{reservationID}": {
            "delete": {
                "description": "Delete reservation by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "Delete Reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "reservation id",
                        "name": "reservationID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/reservation/{reservationId}": {
            "put": {
                "description": "Update reservation by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "Update Reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "reservation id",
                        "name": "reservationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update reservation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reservation.ReservationUpdateEntity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/stays": {
            "get": {
                "description": "Get all stays",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stays"
                ],
                "summary": "Get all stays",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/stays.Stay"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/stays/create": {
            "post": {
                "description": "Create stay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stays"
                ],
                "summary": "Create Stay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of user",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of location",
                        "name": "location_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of stay",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "main image",
                        "name": "image_main",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "images",
                        "name": "images",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "type of stay",
                        "name": "type",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "number of bedrooms",
                        "name": "number_of_bedrooms",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "number of bathrooms",
                        "name": "number_of_beds",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "number of beds",
                        "name": "number_of_bathrooms",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "number of guests",
                        "name": "guests",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "rating",
                        "name": "rating",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "smoking",
                        "name": "is_smoking_prohibited",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "square of home",
                        "name": "square",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "street",
                        "name": "street",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "house",
                        "name": "house",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "entrance if exists",
                        "name": "entrance",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "floor if exists",
                        "name": "floor",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "room if exists",
                        "name": "room",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "price of stay",
                        "name": "price",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/stays/user/{userId}": {
            "get": {
                "description": "Get stays by user id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stays"
                ],
                "summary": "Get all stays by user id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/stays.Stay"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/stays/{stayId}": {
            "get": {
                "description": "get stay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stays"
                ],
                "summary": "Get Stay by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "stay id",
                        "name": "stayId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/stays.Stay"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update stay by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stays"
                ],
                "summary": "Update Stay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "advantage id",
                        "name": "stayId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of location",
                        "name": "location_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of stay",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "main image",
                        "name": "image_main",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "images",
                        "name": "images",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "type of stay",
                        "name": "type",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "number of bedrooms",
                        "name": "number_of_bedrooms",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "number of bathrooms",
                        "name": "number_of_beds",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "number of beds",
                        "name": "number_of_bathrooms",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "number of guests",
                        "name": "guests",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "rating",
                        "name": "rating",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "smoking",
                        "name": "is_smoking_prohibited",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "square of home",
                        "name": "square",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "street",
                        "name": "street",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "house",
                        "name": "house",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "entrance if exists",
                        "name": "entrance",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "floor if exists",
                        "name": "floor",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "room if exists",
                        "name": "room",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "price of stay",
                        "name": "price",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/stays.Stay"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete stay by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stays"
                ],
                "summary": "Delete Stay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "stay id",
                        "name": "stayId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/staysadvantage/create": {
            "post": {
                "description": "Create staysadvantage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staysadvantage"
                ],
                "summary": "Create StaysAdvantage",
                "parameters": [
                    {
                        "description": "stay id",
                        "name": "stay_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "advantage id",
                        "name": "advantage_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        },
        "/staysadvantage/{id}": {
            "delete": {
                "description": "Create staysadvantage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staysadvantage"
                ],
                "summary": "Create StaysAdvantage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "stay advantage id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/responseApi.ResponseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "advantage.Advantage": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "auth.Login": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.Registration": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "location.Location": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "federal_district": {
                    "type": "string"
                },
                "fias_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kladr_id": {
                    "type": "string"
                },
                "lat": {
                    "type": "string"
                },
                "lon": {
                    "type": "string"
                },
                "okato": {
                    "type": "string"
                },
                "oktmo": {
                    "type": "string"
                },
                "population": {
                    "type": "number"
                },
                "region_iso_code": {
                    "type": "string"
                },
                "region_name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "reservation.ReservationEntity": {
            "type": "object",
            "properties": {
                "arrived": {
                    "type": "string"
                },
                "departure": {
                    "type": "string"
                },
                "stay_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "reservation.ReservationUpdateEntity": {
            "type": "object",
            "properties": {
                "arrived": {
                    "type": "string"
                },
                "departure": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "responseApi.ResponseError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "stays.Stay": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "entrance": {
                    "type": "string"
                },
                "floor": {
                    "type": "string"
                },
                "guests": {
                    "type": "integer"
                },
                "house": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_main": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_smoking_prohibited": {
                    "type": "boolean"
                },
                "location_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number_of_bathrooms": {
                    "type": "integer"
                },
                "number_of_bedrooms": {
                    "type": "integer"
                },
                "number_of_beds": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "rating": {
                    "type": "number"
                },
                "room": {
                    "type": "string"
                },
                "square": {
                    "type": "number"
                },
                "street": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "IOD App API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
