basePath: /api/v1
definitions:
  models.Advantage:
    properties:
      created_at:
        type: string
      id:
        type: string
      image:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.Location:
    properties:
      city:
        type: string
      createdAt:
        type: string
      federal_district:
        type: string
      fias_id:
        type: string
      id:
        type: integer
      kladr_id:
        type: string
      lat:
        type: string
      lon:
        type: string
      okato:
        type: string
      oktmo:
        type: string
      population:
        type: number
      region_iso_code:
        type: string
      region_name:
        type: string
      updatedAt:
        type: string
    type: object
  models.Stay:
    properties:
      created_at:
        type: string
      entrance:
        type: string
      floor:
        type: string
      guests:
        type: integer
      house:
        type: string
      id:
        type: string
      image_main:
        type: string
      images:
        items:
          type: string
        type: array
      is_smoking_prohibited:
        type: boolean
      location_id:
        type: string
      name:
        type: string
      number_of_bathrooms:
        type: integer
      number_of_bedrooms:
        type: integer
      number_of_beds:
        type: integer
      price:
        type: number
      rating:
        type: number
      room:
        type: string
      square:
        type: number
      street:
        type: string
      type:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  responseApi.ResponseError:
    properties:
      error:
        type: string
      status:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: IOD App API
  version: "1.0"
paths:
  /advantages/{advantageId}:
    delete:
      consumes:
      - application/json
      description: Delete advantage by id
      parameters:
      - description: advantage id
        in: path
        name: advantageId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: no content
          schema:
            type: string
        "400":
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Delete Advantage
      tags:
      - advantages
    patch:
      consumes:
      - application/json
      description: Update advantage by id
      parameters:
      - description: advantage id
        in: path
        name: advantageId
        required: true
        type: string
      - description: image file
        in: formData
        name: image
        type: file
      - description: title of advantage
        in: formData
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.Advantage'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Update Advantage
      tags:
      - advantages
  /advantages/all:
    get:
      consumes:
      - application/json
      description: Get all advantages
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/models.Advantage'
            type: array
        "400":
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Get advantages
      tags:
      - advantages
  /advantages/create:
    post:
      consumes:
      - multipart/form-data
      description: Create advantage
      parameters:
      - description: image file
        in: formData
        name: image
        required: true
        type: file
      - description: title of advantage
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            $ref: '#/definitions/models.Advantage'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Create Advantage
      tags:
      - advantages
  /locations/{locationName}:
    get:
      consumes:
      - application/json
      description: Find city by matching name
      parameters:
      - description: location name match
        in: path
        name: locationName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/models.Location'
            type: array
        "400":
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Find city by name
      tags:
      - locations
  /stays:
    get:
      consumes:
      - application/json
      description: Get all stays
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/models.Stay'
            type: array
        "400":
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Get all stays
      tags:
      - stays
  /stays/{stayId}:
    get:
      consumes:
      - application/json
      description: get stay
      parameters:
      - description: stay id
        in: path
        name: stayId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.Stay'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Get Stay by id
      tags:
      - stays
  /stays/create:
    post:
      consumes:
      - application/json
      description: Create stay
      parameters:
      - description: id of user
        in: formData
        name: user_id
        required: true
        type: string
      - description: id of location
        in: formData
        name: location_id
        required: true
        type: string
      - description: name of stay
        in: formData
        name: name
        type: string
      - description: main image
        in: formData
        name: image_main
        type: file
      - description: images
        in: formData
        name: images
        type: file
      - description: type of stay
        in: formData
        name: type
        type: string
      - description: number of bedrooms
        in: formData
        name: number_of_bedrooms
        type: integer
      - description: number of bathrooms
        in: formData
        name: number_of_beds
        type: integer
      - description: number of beds
        in: formData
        name: number_of_bathrooms
        type: integer
      - description: number of guests
        in: formData
        name: guests
        type: integer
      - description: rating
        in: formData
        name: rating
        type: number
      - description: smoking
        in: formData
        name: is_smoking_prohibited
        type: boolean
      - description: square of home
        in: formData
        name: square
        type: number
      - description: street
        in: formData
        name: street
        required: true
        type: string
      - description: house
        in: formData
        name: house
        required: true
        type: string
      - description: entrance if exists
        in: formData
        name: entrance
        type: string
      - description: floor if exists
        in: formData
        name: floor
        type: string
      - description: room if exists
        in: formData
        name: room
        type: string
      - description: price of stay
        in: formData
        name: price
        type: number
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            type: string
        "400":
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Create Stay
      tags:
      - stays
swagger: "2.0"
