basePath: /api/v1
definitions:
  auth.Login:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.Registration:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  location.Location:
    properties:
      city:
        type: string
      createdAt:
        type: string
      federal_district:
        type: string
      fias_id:
        type: string
      id:
        type: string
      kladr_id:
        type: string
      lat:
        type: string
      lon:
        type: string
      okato:
        type: string
      oktmo:
        type: string
      population:
        type: number
      region_iso_code:
        type: string
      region_name:
        type: string
      updatedAt:
        type: string
    type: object
  responseApi.ResponseError:
    properties:
      error:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: IOD App API
  version: "1.0"
paths:
  /locations/{locationName}:
    get:
      consumes:
      - application/json
      description: Find city by matching name
      parameters:
      - description: location name match
        in: path
        name: locationName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/location.Location'
            type: array
        "400":
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Find city by name
      tags:
      - locations
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates an existing user and returns a JWT token
      parameters:
      - description: Login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Login an existing user
      tags:
      - auth
  /registration:
    post:
      consumes:
      - application/json
      description: Creates a new user account
      parameters:
      - description: Registration
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.Registration'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responseApi.ResponseError'
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
