name: ci/cd

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: check pwd
        run: pwd
      - name: check files
        run: ls
      - name: Go Mod Tidy
        run: go mod tidy
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: .
      # Generate Swagger documentation
      - name: Generate Swagger Documentation
        run: make swag
        working-directory: .
  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker up
        run: |
          make docker
          # Проверка статуса последней команды
          if [ $? -ne 0 ]; then
          echo "Docker command failed!"
          exit 1
          fi

      - name: Verify deployment
        run: |
          # Replace this with a command to verify the service is running and updated
          curl -f http://localhost:8080/api/v1/swagger/doc.json || exit 1