name: ci/cd

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ./app
      - name: Generate Wire dependency
        run: make wire
        working-directory: .
      - name: Generate Swagger Documentation
        run: make swag
        working-directory: .
      - name: Mocks
        run: make mock
      - name: Test
        run: make test
  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Docker up
        run: |
          make docker-dev
          # Проверка статуса последней команды
          if [ $? -ne 0 ]; then
          echo "Docker command failed!"
          exit 1
          fi

      - name: Verify deployment
        run: |
          # Replace this with a command to verify the service is running and updated
          curl -f http://localhost/api/v1/swagger/doc.json || exit 1
