name: ci/cd

on:
  push:
    branches:
      - main

jobs:
#  swag_and_wire:
#    runs-on: self-hosted
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#      - name: Install Go, Swag, and Wire
#        run: |
#          go install github.com/swaggo/swag/cmd/swag@latest
#          go install github.com/google/wire/cmd/wire@latest
#          echo "export PATH=\$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
#      - name: Swagger
#        run: swag init --md ./docs --parseInternal  --parseDependency --parseDepth 2 -g cmd/app/main.go
#      - name: Wire
#        run: wire ./internal/di

  deploy:
    runs-on: self-hosted
#    needs: swag_and_wire
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check
        run: cat .env
      - name: Len
        run: source .env
      - name: Check comp
        run: cat docker-compose.yml
      - name: Docker up
        run: |
          make docker
          # Проверка статуса последней команды
          if [ $? -ne 0 ]; then
          echo "Docker command failed!"
          exit 1
          fi

      - name: Verify deployment
        run: |
          # Добавьте команду для проверки, что код обновился
          # Например, curl или проверка статуса контейнера