name: ci/cd

on:
  push:
    branches:
      - main

jobs:
  swag_and_wire:
    runs-on: self-hosted
    steps:
      - name: Swagger
        run: make swag
      - name: Wire
        run: make wire
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check
        run: cat .env
      - name: Len
        run: source .env
      - name: Check comp
        run: cat docker-compose.yml
      - name: Docker up
        run: |
          make docker
          # Проверка статуса последней команды
          if [ $? -ne 0 ]; then
          echo "Docker command failed!"
          exit 1
          fi

      - name: Verify deployment
        run: |
          # Добавьте команду для проверки, что код обновился
          # Например, curl или проверка статуса контейнера