name: main

on:
  push:
    branches: [ "main", "ci/cd" ]

jobs:
  postgres_and_migrations:
    runs-on: self-hosted
    steps:
      - name: Docker up
        run: make docker
  deploy:
    runs-on: self-hosted
    needs: postgres_and_migrations
    steps:
      - name: go mod tidy
        run: go mod tidy
      - name: swag and wie
        run: go install github.com/google/wire/cmd/wire@latest && go install github.com/swaggo/swag/cmd/swag@latest
      - name: Run
        run: make run