name: main

on:
  push:
    branches: [ "main", "ci/cd" ]

jobs:
  postgres_and_migrations:
    runs-on: self-hosted
    steps:
      - name: Check
        run: cat .env
      - name: Docker up
        run: make docker