name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  message: "conversation"
  my_token: ${{ secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: [self_hosted]

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker-compose
        run: make docker


  test:
    needs: build
    runs-on: [self-hosted]

    steps:
      - name: Test
        run: make test

#  deploy:
#    needs: test
#    runs-on: [self-hosted]

#    steps:
#      - name: Project publish
