name: main

on:
  push:
    branches: [ "main", "ci/cd" ]

jobs:
  postgres_and_migrations:
    runs-on: self-hosted
    steps:
      - name: Docker up
        run: make docker
  deploy:
    runs-on: self-hosted
    needs: postgres_and_migrations
    steps:
      - name: Check app
        run: go mod tidy
      - name: Run
        run: make run