name: main

on:
  push:
    branches: [ "main", "ci/cd" ]

jobs:
  postgres_and_migrations:
    runs-on: self-hosted
    steps:
      - name: Docker up
        run: make docker
  build:
    runs-on: self-hosted
    steps:
      - name: Install swag
        run: go install github.com/google/wire/cmd/wire@latest
      - name: Install wire
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Build
        run: make build
  deploy:
    runs-on: self-hosted
    steps:
      - name: Run
        run: make run