name: main

on:
  push:
    branches: [ "main" ]

jobs:
  postgres_and_migrations:
    runs-on: self-hosted
    steps:
      - name: Check
        run: cat .env
      - name: Check comp
        run: cat docker-compose.yml
      - name: Docker up
        run: make docker