name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: 3576631-qq34192
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker-compose
        run: make docker