name: main

on:
  push:
    branches: [ "main" ]

jobs:


  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run make docker
        run: make docker
      - name: Build
        run: make build
      - name: Run
        run: make run